const ADMIN_CLIENT_DESCRIPTIONS =
  "ADMIN_CLIENT_DESCRIPTIONS";

const ACTION_ADMIN_CLIENT_DESCRIPTIONS = () => {
  return {
    type: ADMIN_CLIENT_DESCRIPTIONS,
  };
};

export default ACTION_ADMIN_CLIENT_DESCRIPTIONS;
